### ISSUE TITLE
Integer values are converting into float while reading with inferschema

### ISSUE THREAD

**Issue by Manasa81** [elastacloud/spark-excel#26]
Original Data.Check the contractID in original data.
![image](https://github.com/elastacloud/spark-excel/assets/54344129/6e7ae736-3ec1-4be4-8e81-148fe1d23272)
Check after reading with inferschema the .0 has been added to id's
![image](https://github.com/elastacloud/spark-excel/assets/54344129/7d9271b2-3429-4376-849f-ff39d4a08173)

And also unlike csv badrecordspath while reading with schema is not working in this.Did someone tried schema withbadrecordspath?

**Comment by dazfuller** [comment]
Hi

The addition of the ".0" is how the value is being displayed. It does this because the value is a double and this, in turn, is because Excel stores all worksheet numbers as doubles (despite all the options in Excel they end up as doubles). They can be easily cast to integers after extraction though.

The badrecordpath is an interesting one. For things like csv and json the string of the record read so far is written out, but Excel doesn't have a string representation of a record, and so it would need to be converted to a different format before being written out. But could be something that we look at as an option.

**Comment by Manasa81** [comment]
Hi

Thank you for the response

I am reading the dataframe with .schema option expecting all bad records
will go into badrecordsPath given in the options but it keeping null values
in place of badrecords(just like cast option).So, I thought of doing
subtract operation between dataframe(reading without schema option) and
dataframe(with schema option or casted dataframe) to get badrecords. This
logic is working for me for delta sources as delta also won't support
badrecordsPath option. Since the dataframe(reading without schema) has all
the double values in it the subtract/left anti join wouldn't work. So, Is
there is any option to get bad records seperately while reading a folder of
excels with schema?

**Comment by dazfuller** [comment]
Bad records tend to be those which do not comply with the document format, so invalid JSON in a multi-line JSON file, or CSV files where the line doesn't have enough records.

So reading this, are you looking for records which do not conform to the supplied schema?

**Comment by Manasa81** [comment]
Yes
In our case bad records are the records which do not obey schema

**Comment by dazfuller** [comment]
So one of the things that we could do is implement a failure safe parser which would write the data to a "corrupt" column, which you would need to specify in the schema you're passing in. The issue would be working out how to represent the Excel data this way, and there are some who advise against using this, but it would mean that in PERMISSIVE mode you would have a way of getting to that data.

Another option would be to simply check for null values and filter out those rows, especially in instances where you know the column should not contain nulls.

The problem with Excel is you could end up with a lot of these as it's pretty (very) rubbish as a data interchange format, so blank rows, partial rows, etc... would very likely fail a schema check.

**Comment by dazfuller** [comment]
Have a look at the PR #27 and let me know if it's the kind of thing you're looking for

**Comment by Manasa81** [comment]
Hi Darren,


That was very quick
Will check and get back to you

Thank you!

**Comment by dazfuller** [comment]
I'm trying to avoid the list of house chores I need to do 😆

**Comment by Manasa81** [comment]
Lol!

**Comment by Manasa81** [comment]
Hi Darren

Now I'm getting another issue!Could you check is it because of the enhancement.

![image](https://github.com/elastacloud/spark-excel/assets/54344129/8ce0918d-3c00-49f9-a267-743a5c3daf86)

**Comment by dazfuller** [comment]
Weird, that looks like a problem reading the Excel source file. Is there a chance you're able to share it?

**Comment by Manasa81** [comment]
yes, this is the file I was trying to read. I placed this file inside a folder, and I have given folder path in spark read command.
[SampleData.xlsx](https://github.com/elastacloud/spark-excel/files/11540200/SampleData.xlsx)

**Comment by Manasa81** [comment]
Any update on this issue?

**Comment by dazfuller** [comment]
I've loaded up the sample data and can't re-create the error that you're seeing. I'm using a version of the library compiled for Spark 3.3.2 against Databricks Runtime 12.2 LTS

![image](https://github.com/elastacloud/spark-excel/assets/204848/2abc5a23-1cae-4e10-8ff3-5403891abb36)

**Comment by Manasa81** [comment]
I am using DBR of 11.3LTS. Can you downgrade you DBR and try again if possible?
