### ISSUE TITLE
Question config parameters supported

### ISSUE THREAD

**Issue by josecsotomorales** [elastacloud/spark-excel#31]
Hey! First of all nice work on this library, I think you should publish it to MavenCentral. I have questions regarding some customizations I've used in another spark-excel library, will post a set of those, especially for `nullValue` and `treatEmptyValuesAsNulls`, are those currently available or easy to add? If not, how does this library currently treat empty values?

```
  private val ExcelOptions = Map[String, String](
    "header" -> "true",
    "treatEmptyValuesAsNulls" -> "true",
    "nullValue" -> null,
    "emptyValue" -> null,
    "setErrorCellsToFallbackValues" -> "false",
    "inferSchema" -> "false",
    "usePlainNumberFormat" -> "false",
    "addColorColumns" -> "false",
    "excerptSize" -> "10",
    "tempFileThreshold" -> "100000000",
    "maxRowsInMemory" -> "20"
  )
```

**Comment by josecsotomorales** [comment]
From what I'm seeing on the code it seems like empty values are treated as null: https://github.com/elastacloud/spark-excel/blob/c2511abdfa9dca211151e3a70873c42aca30d255/src/main/scala/com/elastacloud/spark/excel/parser/ExcelParser.scala#L270C33-L270C33

**Comment by dazfuller** [comment]
Hey, thanks for the feedback, it's always nice to hear :)

I've been wanting to push this out to maven central, but honestly, I'm still trying to work that bit out as it's an uber-jar and everything I see is saying "DON'T".

So you are right, the handling of null values is performed by the `getCellValue` function which will return null if the cell value is None, Blank, or an Error, it will also return null if the source type of the cell cannot be converted to the schema target type. Adding a new option which allows for custom values to be treated as nulls as well (e.g. "NA") should be pretty straightforward as it would just need a new line in the string value handling section to see if the cell value matches the null option value.

**Comment by josecsotomorales** [comment]
@dazfuller I don't see any issues with pushing an uber jar to Maven central, lot of Spark dependencies already do that because of conflicting guava, hikari, and other lib versions that come with the Spark jars

**Comment by dazfuller** [comment]
I should probably learn how to publish maven central then

**Comment by dazfuller** [comment]
Always happy to accept help :)
